services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: directory_service
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5348:5341" # Seq UI and API
      - "80:80"   # Optional: For HTTP ingestion (e.g., Serilog HTTP)
    volumes:
      - seq_data:/data # Persistent storage for Seq data
    

volumes:
    postgres-data:
    seq_data: